#ifndef GLOBALS_H
#define GLOBALS_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200
#define MAP_WIDTH 24
#define MAP_HEIGHT 24

#define MOVE_SPEED 5
#define ROTATE_SPEED 3

#define TEXTURE_WIDTH 64
#define TEXTURE_HEIGHT (TEXTURE_WIDTH)

#endif
